# Generated by Django 2.2.2 on 2019-06-10 10:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('duration', models.IntegerField(help_text='Total time duration(in days)')),
                ('days', models.IntegerField(blank=True, null=True)),
                ('nights', models.IntegerField(blank=True, null=True)),
                ('price', models.FloatField(help_text='Price per person')),
                ('group_size', models.IntegerField(blank=True, null=True)),
                ('departure_from', models.CharField(blank=True, max_length=100, null=True)),
                ('destination', models.CharField(max_length=100)),
                ('meal_service', models.IntegerField(blank=True, help_text='Served meals per day', null=True)),
                ('introduction', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('review', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('review_date', models.DateTimeField(auto_now=True)),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trek.Package')),
            ],
            options={
                'ordering': ['review_date'],
            },
        ),
    ]
