# Generated by Django 2.2.2 on 2019-06-10 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trek', '0003_auto_20190610_1028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='speciality',
            field=models.CharField(blank=True, choices=[('Awesome', 'Awesome Tour'), ('Best', 'Best Offer'), ('Special', 'Special Package'), ('Popular', 'Popular Tour')], max_length=50, null=True),
        ),
    ]
