# Generated by Django 2.2.2 on 2019-06-10 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trek', '0004_auto_20190610_1037'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='activities',
            field=models.CharField(blank=True, help_text='Activities included in the package(separate with comma)', max_length=500, null=True),
        ),
    ]
