# Generated by Django 2.2.2 on 2019-06-10 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trek', '0005_package_activities'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='package',
            name='activities',
        ),
        migrations.AddField(
            model_name='package',
            name='activities',
            field=models.ManyToManyField(help_text='Activities included in the package', to='trek.Activity'),
        ),
    ]
