# Generated by Django 2.2.2 on 2019-06-23 06:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trek', '0009_auto_20190623_0618'),
    ]

    operations = [
        migrations.CreateModel(
            name='PackageItinerary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.IntegerField(help_text='Number of day(1, 2, 3, etc.)')),
                ('place', models.CharField(max_length=200)),
                ('sub_heading', models.CharField(blank=True, max_length=200, null=True)),
                ('description', models.TextField()),
                ('meals', models.IntegerField(blank=True, help_text='Served meals (in number)', null=True)),
                ('altitude', models.CharField(blank=True, help_text='Altitude of the place', max_length=100, null=True)),
                ('accomodation', models.CharField(blank=True, help_text='Type of Accomodation', max_length=50, null=True)),
                ('travel', models.CharField(blank=True, help_text='Type of travel', max_length=50, null=True)),
                ('image', models.ImageField(upload_to='package/itinerary/')),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itinerary', to='trek.Package')),
            ],
        ),
        migrations.CreateModel(
            name='PackageCostIncluded',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('included_items', models.CharField(default='', max_length=200)),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cost_included', to='trek.Package')),
            ],
        ),
        migrations.CreateModel(
            name='PackageCostExluded',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('excluded_items', models.CharField(default='', max_length=200)),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cost_excluded', to='trek.Package')),
            ],
        ),
    ]
