# Generated by Django 2.2.2 on 2019-07-01 15:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trek', '0010_packagecostexluded_packagecostincluded_packageitinerary'),
    ]

    operations = [
        migrations.CreateModel(
            name='TripBooking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(blank=True, null=True)),
                ('title', models.CharField(choices=[('mr.', 'Mr'), ('mrs.', 'Mrs.'), ('ms.', 'Miss')], max_length=10)),
                ('first_name', models.CharField(max_length=100)),
                ('middle_name', models.CharField(blank=True, max_length=100, null=True)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=100)),
                ('passport_number', models.CharField(max_length=50)),
                ('place_of_issue', models.CharField(max_length=100)),
                ('issue_date', models.DateField()),
                ('expire_date', models.DateField()),
                ('emergency_contact_number', models.CharField(max_length=100)),
                ('booking_date', models.DateTimeField(auto_now=True, null=True)),
                ('nationality', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trip_book', to='trek.Country')),
                ('trip_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='book', to='trek.Package')),
            ],
            options={
                'ordering': ['booking_date'],
            },
        ),
    ]
