# Generated by Django 2.2.2 on 2019-07-01 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trek', '0011_tripbooking'),
    ]

    operations = [
        migrations.CreateModel(
            name='TripPersonalInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(choices=[('mr.', 'Mr'), ('mrs.', 'Mrs.'), ('ms.', 'Miss')], max_length=10)),
                ('first_name', models.CharField(max_length=100)),
                ('middle_name', models.CharField(blank=True, max_length=100, null=True)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=100)),
                ('passport_number', models.CharField(max_length=50)),
                ('place_of_issue', models.CharField(max_length=100)),
                ('issue_date', models.DateField()),
                ('expire_date', models.DateField()),
                ('emergency_contact_number', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='tripbooking',
            name='email',
        ),
        migrations.RemoveField(
            model_name='tripbooking',
            name='emergency_contact_number',
        ),
        migrations.RemoveField(
            model_name='tripbooking',
            name='expire_date',
        ),
        migrations.RemoveField(
            model_name='tripbooking',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='tripbooking',
            name='issue_date',
        ),
        migrations.RemoveField(
            model_name='tripbooking',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='tripbooking',
            name='middle_name',
        ),
        migrations.RemoveField(
            model_name='tripbooking',
            name='passport_number',
        ),
        migrations.RemoveField(
            model_name='tripbooking',
            name='phone_number',
        ),
        migrations.RemoveField(
            model_name='tripbooking',
            name='place_of_issue',
        ),
        migrations.RemoveField(
            model_name='tripbooking',
            name='title',
        ),
    ]
