# Generated by Django 2.2.2 on 2019-07-01 15:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trek', '0012_auto_20190701_1522'),
    ]

    operations = [
        migrations.AddField(
            model_name='trippersonalinfo',
            name='trip_book',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='trek.TripBooking'),
        ),
    ]
