# Generated by Django 2.2.2 on 2019-07-02 15:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trek', '0013_trippersonalinfo_trip_book'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='address',
            new_name='contact',
        ),
        migrations.AddField(
            model_name='review',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='trek.Country'),
        ),
    ]
