# Generated by Django 2.2.2 on 2019-07-03 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trek', '0015_auto_20190702_1554'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('author', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('image', models.ImageField(upload_to='blogs/')),
                ('content', models.TextField()),
            ],
        ),
    ]
