# Generated by Django 2.2.2 on 2019-07-13 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trek', '0016_blog'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='accepted',
            field=models.BooleanField(default=False),
        ),
    ]
