# Generated by Django 2.2.2 on 2019-07-13 10:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trek', '0017_review_accepted'),
    ]

    operations = [
        migrations.CreateModel(
            name='PackageRating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rating', to='trek.Package')),
            ],
        ),
    ]
