# Generated by Django 2.2.2 on 2019-07-13 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trek', '0018_packagerating'),
    ]

    operations = [
        migrations.AddField(
            model_name='packagerating',
            name='rating',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='review',
            name='rating',
            field=models.IntegerField(default=0),
        ),
    ]
