# Generated by Django 2.2.2 on 2019-07-13 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trek', '0019_auto_20190713_1011'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='rating',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True),
        ),
        migrations.DeleteModel(
            name='PackageRating',
        ),
    ]
