# Generated by Django 2.2.5 on 2019-09-19 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trek', '0020_auto_20190713_1034'),
    ]

    operations = [
        migrations.AddField(
            model_name='headerimage',
            name='banner_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='headerimage',
            name='banner_title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
