# Generated by Django 2.2.5 on 2019-09-19 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trek', '0021_auto_20190919_0923'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutUsDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about_description', models.TextField()),
            ],
        ),
    ]
