# Generated by Django 2.2.5 on 2019-09-19 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trek', '0022_aboutusdetail'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutusdetail',
            name='video_url',
            field=models.CharField(blank=True, help_text='Paste the youtube video url here', max_length=100, null=True),
        ),
    ]
