# Generated by Django 2.2.5 on 2019-09-19 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trek', '0023_aboutusdetail_video_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutusdetail',
            name='address',
            field=models.CharField(blank=True, help_text='Your address', max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='aboutusdetail',
            name='contact_number',
            field=models.CharField(blank=True, help_text='Your contact Number', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='aboutusdetail',
            name='email',
            field=models.CharField(blank=True, help_text='Your email address', max_length=255, null=True),
        ),
    ]
