# Generated by Django 2.2.5 on 2019-09-23 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trek', '0024_auto_20190919_0958'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trippersonalinfo',
            name='emergency_contact_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='trippersonalinfo',
            name='expire_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='trippersonalinfo',
            name='issue_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='trippersonalinfo',
            name='passport_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='trippersonalinfo',
            name='place_of_issue',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
