# Generated by Django 2.2.5 on 2019-09-23 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trek', '0025_auto_20190923_0548'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='package',
            name='days',
        ),
        migrations.RemoveField(
            model_name='package',
            name='group_size',
        ),
        migrations.RemoveField(
            model_name='package',
            name='meal_service',
        ),
        migrations.RemoveField(
            model_name='package',
            name='nights',
        ),
        migrations.RemoveField(
            model_name='packageitinerary',
            name='place',
        ),
        migrations.AlterField(
            model_name='blog',
            name='image',
            field=models.ImageField(help_text='Image size: width=370px height=370px', upload_to='blogs/'),
        ),
        migrations.AlterField(
            model_name='happyclient',
            name='cover_picture',
            field=models.ImageField(help_text='Image size: width=350px height=120px', upload_to='clients/cover/'),
        ),
        migrations.AlterField(
            model_name='happyclient',
            name='profile_picture',
            field=models.ImageField(help_text='Image size: width=65px height=65px', upload_to='clients/profile/'),
        ),
        migrations.AlterField(
            model_name='headerimage',
            name='image',
            field=models.ImageField(help_text='Image size: width=1800px; height=600px', upload_to='header/'),
        ),
        migrations.AlterField(
            model_name='packageimage',
            name='image',
            field=models.ImageField(help_text='Image size: width=360px height=245px', upload_to='package/images/'),
        ),
        migrations.AlterField(
            model_name='photogallery',
            name='image',
            field=models.ImageField(help_text='Image size: width=350px height=350px', upload_to='gallery/'),
        ),
    ]
