# Generated by Django 2.2.5 on 2019-09-23 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trek', '0026_auto_20190923_0557'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='days',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='package',
            name='group_size',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='package',
            name='meal_service',
            field=models.IntegerField(blank=True, help_text='Served meals per day', null=True),
        ),
        migrations.AddField(
            model_name='package',
            name='nights',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
