# Generated by Django 2.2.5 on 2019-09-25 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trek', '0028_auto_20190923_0635'),
    ]

    operations = [
        migrations.RenameField(
            model_name='packageitinerary',
            old_name='sub_heading',
            new_name='place',
        ),
        migrations.AddField(
            model_name='packageitinerary',
            name='place_description',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='packageitinerary',
            name='accomodation',
            field=models.CharField(blank=True, help_text='Type of Accomodation (Example: Hotel, Camp, etc.)', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='packageitinerary',
            name='travel',
            field=models.CharField(blank=True, help_text='Type of travel (Example: Bus, Plane, Train, etc.)', max_length=50, null=True),
        ),
    ]
