# Generated by Django 2.2.5 on 2019-09-25 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trek', '0029_auto_20190925_0828'),
    ]

    operations = [
        migrations.AlterField(
            model_name='packageitinerary',
            name='image',
            field=models.ImageField(help_text='Image size: width=376px height=376px ', upload_to='package/itinerary/'),
        ),
    ]
