# Generated by Django 2.2.5 on 2019-11-10 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trek', '0030_auto_20190925_0847'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='map_image',
            field=models.ImageField(blank=True, null=True, upload_to='package/map/'),
        ),
    ]
