# Generated by Django 2.2.5 on 2019-11-18 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trek', '0031_package_map_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='font_awesome_code',
            field=models.CharField(blank=True, help_text='Paste a font awesome code for activity icon here(e.g. fa-mountain, fa-hiking)', max_length=50, null=True),
        ),
    ]
