# Generated by Django 2.2.5 on 2019-11-29 06:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trek', '0032_activity_font_awesome_code'),
    ]

    operations = [
        migrations.RenameField(
            model_name='package',
            old_name='days',
            new_name='minimum_group_size',
        ),
        migrations.RemoveField(
            model_name='package',
            name='group_size',
        ),
        migrations.RemoveField(
            model_name='package',
            name='meal_service',
        ),
        migrations.RemoveField(
            model_name='package',
            name='nights',
        ),
    ]
