# Generated by Django 2.2.5 on 2019-11-29 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trek', '0033_auto_20191129_0612'),
    ]

    operations = [
        migrations.AddField(
            model_name='trippersonalinfo',
            name='group_of_people',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trippersonalinfo',
            name='number_of_children',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='customtrip',
            name='country',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='tripbooking',
            name='nationality',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
