# Generated by Django 2.2.5 on 2019-11-29 06:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trek', '0034_auto_20191129_0615'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trippersonalinfo',
            old_name='number_of_children',
            new_name='are_children_included',
        ),
    ]
