# Generated by Django 2.2.5 on 2019-11-29 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trek', '0036_auto_20191129_0658'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogBannerImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(help_text='Image size: width=1803px height=380px', upload_to='banner/blogs/')),
            ],
        ),
    ]
