# Generated by Django 2.2.5 on 2019-12-01 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trek', '0037_blogbannerimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='packageitinerary',
            name='outline',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
