# Generated by Django 2.2.5 on 2019-12-01 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trek', '0038_packageitinerary_outline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='packageitinerary',
            name='outline',
            field=models.TextField(blank=True, null=True),
        ),
    ]
