# Generated by Django 2.2.5 on 2019-12-04 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trek', '0040_headerimage_package'),
    ]

    operations = [
        migrations.AddField(
            model_name='trippersonalinfo',
            name='people_above_60_age',
            field=models.IntegerField(default=0, help_text='Number of people above 60 years of age'),
        ),
    ]
