# Generated by Django 2.2.5 on 2019-12-04 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trek', '0041_trippersonalinfo_people_above_60_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='available',
            field=models.BooleanField(default=True),
        ),
    ]
