# Generated by Django 2.2.5 on 2019-12-07 10:20

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('trek', '0043_auto_20191204_1003'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='desc',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
    ]
