# Generated by Django 2.2.5 on 2019-12-07 10:25

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('trek', '0044_package_desc'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='package',
            name='desc',
        ),
        migrations.AlterField(
            model_name='aboutusdetail',
            name='about_description',
            field=tinymce.models.HTMLField(),
        ),
        migrations.AlterField(
            model_name='blog',
            name='content',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='package',
            name='introduction',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='packageitinerary',
            name='description',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='packageitinerary',
            name='outline',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
    ]
