# Generated by Django 2.2.5 on 2019-12-08 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trek', '0046_aboutusdetail_whatsapp_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='hidden',
            field=models.BooleanField(default=False),
        ),
    ]
