# Generated by Django 2.2.5 on 2019-12-09 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trek', '0049_generic'),
    ]

    operations = [
        migrations.AddField(
            model_name='generic',
            name='section',
            field=models.CharField(choices=[('About_Nepal', 'About Nepal'), ('Before_Visit', 'Before You Come')], default='', max_length=500),
        ),
    ]
