# Generated by Django 2.2.5 on 2019-12-09 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trek', '0050_generic_section'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generic',
            name='section',
            field=models.CharField(choices=[('About_Nepal', 'About Nepal'), ('Before_Visit', 'Before You Come'), ('Popular_Links', 'The Popular Links')], default='', max_length=500),
        ),
    ]
