# Generated by Django 2.2.5 on 2019-12-16 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trek', '0053_paymentprocess'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generic',
            name='image',
            field=models.ImageField(blank=True, help_text='Image size: width=746px height=300px', null=True, upload_to='generics/'),
        ),
    ]
