# Generated by Django 2.2.5 on 2019-12-16 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trek', '0054_auto_20191216_0432'),
    ]

    operations = [
        migrations.AlterField(
            model_name='packageitinerary',
            name='image',
            field=models.ImageField(blank=True, help_text='Image size: width=376px height=376px ', null=True, upload_to='package/itinerary/'),
        ),
    ]
