# Generated by Django 2.2.5 on 2019-12-17 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trek', '0056_auto_20191217_1347'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='short_info',
            field=models.TextField(blank=True, null=True),
        ),
    ]
