# Generated by Django 2.2.9 on 2020-01-29 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trek', '0058_auto_20200129_0530'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutusdetail',
            name='logo',
            field=models.ImageField(blank=True, help_text='Image size: width: 258px, height: 69px', null=True, upload_to='logo/'),
        ),
    ]
